#!/bin/bash

# curl job poster to kue's JSON API


### VARS

HOST="http://localhost"
PORT=3333
#challengeId=null
#messageId=null
#createdBy=null
#createdAt=null
#content=''
challengeId=3
messageId=1
createdBy=1234
createdAt='2014-12-10T01:00:00.000'
content='this is a test post by user 1234(fake user since all the particpants are 40015035) the test email should be sent 3 times'
attempts=3
priority='normal'


# Read argumnets
while [ "$1" != "" ]; do
    case $1 in
        -h | --host )           shift
                                HOST=$1
                                ;;
        -p | --port )           shift
                                PORT=$1
                                ;;
        -cId | --challengeId )  shift
                                challengeId=$1
                                ;;
        -mId | --messageId )    shift
                                messageId=$1
                                ;;
        -cBy | --createdBy )    shift
                                createdBy=$1
                                ;;
        -cAt | --createdAt )    shift
                                createdAt=$1
                                ;;
        -c | --content )        shift
                                content=$1
                                ;;
        -a | --attempts )       shift
                                attempts=$1
                                ;;
        -pr | --priority )      shift
                                priority=$1
                                ;;
    esac
    shift
done

# Create payload
BODY='{
   "type": "60_new_discussion_message",
   "data": {
     "title": "Challenge '$challengeId' got new discussion message",
     "challengeId": '$challengeId',
     "messageId": '$messageId',
     "createdBy": '$createdBy',
     "createdAt": "'$createdAt'",
     "content": "'$content'"
   },
   "options" : {
     "attempts": '$attempts',
     "priority": "'$priority'"
   }
}'

# Dump it
echo "posting to $HOST:$PORT/job the following data:"
echo $BODY
echo


# POST the job
RES=$(curl  -H "Content-Type: application/json" -X POST -d "$BODY" $HOST:$PORT/job)

# if you are using basic auth on the kue server you will need curl --user username:password


# Print the results
echo $RES
